import { PlanTier } from "../types";

export const subscription_plans: PlanTier[] = [
  {
    id: "package-1",
    packageNumber: "PACKAGE 1",
    name: "Sprint Lite",
    tagline: "High-converting landing pages & quick MVP launches",
    upfrontFee: 4499,
    monthlySupportFee: 599,
    supportCommitmentMonths: 3,
    turnaroundDays: "5–7 Days Delivery",
    pageCount: "1–2 Pages",
    iterationPolicy: "2 Revision Rounds",
    concurrentRequests: 1,
    popular: false,
    bgHighlightColor: "teal",
    textColor: "ink",
    bgColor: "page",
    dotColor: "#aee812",
    buttonLabel: "Select Package 1",
    description: "A focused, fast build for businesses and founders needing a crisp, high-performing web presence launched fast.",
    highlights: ["1–2 Custom Designed Pages", "Fast 5–7 Day Delivery & Launch", "2 Design & Content Revision Rounds", "Ultra-Fast Mobile Speed & SEO Setup", "Lead Capture & Contact Form Integration", "100% Full Code & Domain Ownership"],
    features: [
      { id: "scope", name: "1–2 Bespoke Designed Pages", included: true },
      { id: "turnaround", name: "5–7 Business Days Delivery", included: true },
      { id: "revisions", name: "2 Design & Copy Revision Rounds", included: true },
      { id: "seo-speed", name: "95+ Core Web Vitals & SEO Meta", included: true },
      { id: "ownership", name: "100% Full Code & Domain Ownership", included: true },
      { id: "hosting", name: "Managed Cloud Hosting & SSL", included: true },
      { id: "cms", name: "Headless CMS (Sanity / Framer)", included: false, unavailableNote: "Static Code" },
      { id: "motion", name: "Interactive Motion & Physics FX", included: false, unavailableNote: "Basic CSS" },
      { id: "comms", name: "Direct Shared Slack Channel", included: false, unavailableNote: "Email Only" },
      { id: "auth-db", name: "User Accounts & Database Backend", included: false, unavailableNote: "Not Included" },
      { id: "velocity", name: "Dual-Track Engineering (2 Tasks)", included: false, unavailableNote: "1 Track Only" },
    ],
    specs: [
      { label: "Build Scope", value: "1–2 Bespoke Pages" },
      { label: "Delivery Pace", value: "5–7 Business Days" },
      { label: "Revisions", value: "2 Structured Rounds" },
      { label: "Tech Stack", value: "Next.js & Tailwind CSS" },
      { label: "Hosting & Domain", value: "Configured & Managed" },
      { label: "Support SLA", value: "Email Support (48h reply)" },
    ],
    includedFeatures: ["High-converting, responsive layout for all devices", "Speed optimization & Google search preview tags", "Lead capture form delivered straight to your inbox", "Full source code and deployment handover"],
    supportIncludes: ["Managed cloud hosting & SSL security", "Monthly software updates & security checks", "Up to 2 content or text edits each month", "Zero cancellation fees after month 6"],
  },
  {
    id: "package-2",
    packageNumber: "PACKAGE 2",
    name: "Studio Growth",
    tagline: "Complete multi-page site with CMS & ongoing design sprints",
    upfrontFee: 9999,
    monthlySupportFee: 599,
    supportCommitmentMonths: 3,
    turnaroundDays: "2–3 Weeks Launch",
    pageCount: "4–6 Pages + CMS",
    iterationPolicy: "Unlimited Iterations",
    concurrentRequests: 1,
    popular: true,
    bgHighlightColor: "lavender",
    textColor: "ink",
    bgColor: "page",
    dotColor: "#aee812",
    buttonLabel: "Select Package 2",
    description: "Our most popular package. A multi-page site with an easy-to-use CMS, custom motion, and active monthly iterations to keep your site fresh.",
    highlights: ["4–6 Pages + Easy-to-Use CMS Blog/Cases", "2–3 Weeks Launch Pace (Tasks in 48–72h)", "Unlimited Iterations Until You Love It", "Interactive Micro-Animations & Motion", "Analytics & Conversion Tracking Setup", "Dedicated Direct Slack with Our Team"],
    features: [
      { id: "scope", name: "4–6 Custom Pages + CMS Blog/Cases", included: true, badge: "Popular" },
      { id: "turnaround", name: "2–3 Weeks Launch Pace", included: true },
      { id: "revisions", name: "Unlimited Iterations Until Launch", included: true, badge: "Unlimited" },
      { id: "seo-speed", name: "95+ Core Web Vitals & SEO Meta", included: true },
      { id: "ownership", name: "100% Full Code & Domain Ownership", included: true },
      { id: "hosting", name: "Managed Cloud Hosting & SSL", included: true },
      { id: "cms", name: "Headless CMS (Sanity / Framer setup)", included: true },
      { id: "motion", name: "Interactive Motion & Physics FX", included: true },
      { id: "comms", name: "Direct Shared Slack Channel", included: true },
      { id: "auth-db", name: "User Accounts & Database Backend", included: false, unavailableNote: "Requires P3" },
      { id: "velocity", name: "Dual-Track Engineering (2 Tasks)", included: false, unavailableNote: "1 Track Only" },
    ],
    specs: [
      { label: "Build Scope", value: "4–6 Pages + Headless CMS" },
      { label: "Delivery Pace", value: "2–3 Weeks to Launch" },
      { label: "Revisions", value: "Unlimited Iterations" },
      { label: "Tech Stack", value: "Next.js, Motion, Sanity/Framer" },
      { label: "CMS Collections", value: "Blog, Case Studies, FAQs" },
      { label: "Support SLA", value: "Direct Slack (Same-day reply)" },
    ],
    includedFeatures: ["Everything in Package 1", "Self-serve CMS to update content in seconds", "Engaging interactive motion & micro-details", "Shared staging preview to review before launch"],
    supportIncludes: ["Active monthly design & dev iterations", "Fast turnaround for new pages & section tests", "Managed cloud hosting, backups & uptime monitoring", "Dedicated Slack channel with your developers", "Cancel anytime after 3 months with zero penalty"],
  },
  {
    id: "package-3",
    packageNumber: "PACKAGE 3",
    name: "Full-Stack Custom",
    tagline: "Custom web application, user accounts & priority sprint velocity",
    upfrontFee: 25499,
    monthlySupportFee: 799,
    supportCommitmentMonths: 3,
    turnaroundDays: "Priority 24–48h SLA",
    pageCount: "Unlimited Pages",
    iterationPolicy: "Infinite Iterations",
    concurrentRequests: 2,
    popular: false,
    bgHighlightColor: "coral",
    textColor: "ink",
    bgColor: "page",
    dotColor: "#aee812",
    buttonLabel: "Select Package 3",
    description: "For growing businesses requiring custom web apps, dynamic customer portals, and dedicated senior engineering velocity.",
    highlights: ["Unlimited Pages & Custom Web Application", "Fast 24–48 Hour Priority Turnaround SLA", "Customer Portals, Auth & Database Integration", "2 Simultaneous Active Engineering Tasks", "VIP Dedicated Slack & Weekly Video Check-Ins"],
    features: [
      { id: "scope", name: "Unlimited Pages & Custom Web App", included: true, badge: "Full App" },
      { id: "turnaround", name: "Priority 24–48h SLA Delivery", included: true, badge: "VIP Speed" },
      { id: "revisions", name: "Infinite Iterations & Adjustments", included: true },
      { id: "seo-speed", name: "95+ Core Web Vitals & SEO Meta", included: true },
      { id: "ownership", name: "100% Full Code & Domain Ownership", included: true },
      { id: "hosting", name: "Managed Cloud Hosting & SSL", included: true },
      { id: "cms", name: "Headless CMS & Custom Schemas", included: true },
      { id: "motion", name: "Interactive Motion & Physics FX", included: true },
      { id: "comms", name: "VIP Slack + Weekly Video Sync", included: true },
      { id: "auth-db", name: "User Accounts & Database Backend", included: true },
      { id: "velocity", name: "Dual-Track Engineering (2 Tasks)", included: true, badge: "2x Speed" },
    ],
    specs: [
      { label: "Build Scope", value: "Unlimited Pages & Custom App" },
      { label: "Delivery Pace", value: "Priority VIP Sprints (24–48h)" },
      { label: "Revisions", value: "Infinite Iterations" },
      { label: "Tech Stack", value: "Next.js, Node.js, Postgres/Supabase" },
      { label: "Integrations", value: "Auth, APIs & Webhooks" },
      { label: "Support SLA", value: "VIP Slack + Weekly Calls" },
    ],
    includedFeatures: ["Everything in Package 2", "End-to-end user authentication & database schemas", "Two simultaneous development tracks for double speed"],
    supportIncludes: ["Dedicated lead developer on active retainer", "Continuous new feature build-out & scaling", "Database monitoring, security & performance audits", "Weekly video calls with founding engineers", "Cancel anytime after 3 months with full documentation"],
  },
];

export const contraqt_faq = [
  {
    q: "How does the contract structure work (Upfront Fee + 3-Month Plan)?",
    a: "Every project begins with an upfront fee covering the complete bespoke design, engineering, testing, and production launch of your website. Upon launch, your 3-month support plan activates (290 kr, 590 kr, or 1,250 kr/mo depending on your package). This guarantees your site is actively maintained, securely hosted, and continuously iterated by our engineers.",
  },
  {
    q: "What happens after the 3-month obligatory period ends?",
    a: "You have complete flexibility! You can choose to stop your plan with zero cancellation fees, at which point our active support and continuous development ends (you retain 100% full ownership of your code, design, and domain). Or, you can choose to continue month-to-month to keep our team actively building for you.",
  },
  {
    q: "Why do you have a 3-month support commitment?",
    a: "Great websites are living products, not static brochures. The 6-month term ensures that post-launch, we are right by your side to analyze real user traffic, optimize conversion rates, deploy new content updates, fix browser quirks, and guarantee 99.9% uptime while your business scales.",
  },
  {
    q: "What does submitting the inquiry form do?",
    a: "When you submit the form, our system immediately sends you a detailed confirmation email with a copy of your project brief, contract specifications, and onboarding overview. Simultaneously, our founders receive an alert with your details. We review your request and get back to you within 24 business hours to lock in your kickoff date.",
  },
  {
    q: "Can I add custom features or change packages later?",
    a: "Yes. If your needs grow during the build or support phase, you can seamlessly upgrade tiers or request bespoke add-ons directly with your lead engineer.",
  },
];
